export const Products = [
    {
        id:1,
        name:"jeans",
        price:"1500",
        image:""
    },
    {
        id:2,
        name:"jeans",
        price:"2500",
        image:""
    },
    {
        id:3,
        name:"jeans",
        price:"1700",
        image:""
    },
    {
        id:4,
        name:"jeans",
        price:"1200",
        image:""
    },
    {
        id:5,
        name:"jeans",
        price:"1100",
        image:""
    },
    {
        id:6,
        name:"jeans",
        price:"1900",
        image:""
    },
    {
        id:7,
        name:"shirt",
        price:"1500",
        image:""
    },{
        id:8,
        name:"shirt",
        price:"1300",
        image:""
    },{
        id:9,
        name:"shirt",
        price:"1700",
        image:""
    },{
        id:10,
        name:"shirt",
        price:"1800",
        image:""
    },{
        id:11,
        name:"shirt",
        price:"1200",
        image:""
    },{
        id:12,
        name:"shirt",
        price:"1400",
        image:""
    },

]
